version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  build:
    commands:
      - echo "Andy Primawan - CI/CD Pipeline for Spring Boot using AWS"
      - ./gradlew bootJar

artifacts:
  files:
    - 'build/libs/demo-0.0.1-SNAPSHOT.jar'
  name: springboot
  discard-paths: yes
